
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RANGO_CHAR = 29;
  public static final int COMILLA_D = 17;
  public static final int GUION = 3;
  public static final int DOSPT = 8;
  public static final int RANGO_MAYUS = 24;
  public static final int OR = 19;
  public static final int CONJUNTO = 2;
  public static final int CHAR = 31;
  public static final int RANGO_MINUS = 25;
  public static final int UNO_MAS = 21;
  public static final int SNUMS = 27;
  public static final int CONCAT = 18;
  public static final int PAR_C = 10;
  public static final int PAR_A = 9;
  public static final int COR_C = 12;
  public static final int SCHAR = 30;
  public static final int COR_A = 11;
  public static final int PORCEN = 15;
  public static final int COMA = 7;
  public static final int MAYORQ = 5;
  public static final int EOF = 0;
  public static final int SLETRAS = 26;
  public static final int CERO_UNO = 22;
  public static final int error = 1;
  public static final int COMILLA_S = 16;
  public static final int RANGO_NUM = 28;
  public static final int CERO_MAS = 20;
  public static final int LLAVE_C = 14;
  public static final int LLAVE_A = 13;
  public static final int RANGO = 4;
  public static final int TITULO = 23;
  public static final int PTCOMA = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJUNTO",
  "GUION",
  "RANGO",
  "MAYORQ",
  "PTCOMA",
  "COMA",
  "DOSPT",
  "PAR_A",
  "PAR_C",
  "COR_A",
  "COR_C",
  "LLAVE_A",
  "LLAVE_C",
  "PORCEN",
  "COMILLA_S",
  "COMILLA_D",
  "CONCAT",
  "OR",
  "CERO_MAS",
  "UNO_MAS",
  "CERO_UNO",
  "TITULO",
  "RANGO_MAYUS",
  "RANGO_MINUS",
  "SLETRAS",
  "SNUMS",
  "RANGO_NUM",
  "RANGO_CHAR",
  "SCHAR",
  "CHAR"
  };
}

